### ISSUE TITLE
nested statements

### ISSUE THREAD

**Issue by wshayes** [belbio/bel_api#35]
Getting an error parsing/validating the following:

belstmt validate "abundance(CHEBI:antioxidant) decreases (abundance(SCHEM:\"7-Ketocholesterol\") increases biologicalProcess(GO:\"apoptotic process\"))"

**Comment by davidchen** [comment]
Fixed under https://github.com/belbio/bel_lang/commit/b3f46c3844257e5477ade06abb35bbcf57b056e2.
